### ISSUE TITLE
Laravel 8.x support

### ISSUE THREAD

**Issue by davi5e** [skydiver/nova-update-card#17]
Should be a simple change to [guzzlehttp/guzzle](https://github.com/guzzle/guzzle) `^7.0.1` as a requirement.

**Comment by skydiver** [comment]
hey @davi5e, the problem is related to `knplabs/packagist-api` dependency, is still using an old version of guzzle.
I'm gonna replace the package and manually fetch the laravel version...

**Comment by skydiver** [comment]
@davi5e fixed on v1.5.0 🎆
