### ISSUE TITLE
Call to a member function find() on null

### ISSUE THREAD

**Issue by bernhardh** [skydiver/nova-update-card#20]
Since some days, I am getting the error `Call to a member function find() on null` in `vendor/skydiver/nova-update-card/src/Http/Controllers/UpdateController.php:40`

**Comment by bernhardh** [comment]
Thats probably because they changed the content of https://nova.laravel.com/releases

**Comment by skydiver** [comment]
Thanks @bernhardh 

This was fixed on v1.5.1
